MARGIN = 10
SIDE = 60
SUDOKU_BOX_SIZE = 3
SUDOKU_SIZE = SUDOKU_BOX_SIZE ** 2
SUDOKU_WIDTH = SUDOKU_HEIGHT = MARGIN * 2 + SIDE * SUDOKU_SIZE
WIDTH = 3 * SUDOKU_WIDTH
HEIGHT = SUDOKU_HEIGHT + 100
BUTTON_WIDTH = 10
BUTTON_COLUMNS = tuple(range(0, 10, 2))
BUTTON_ROWS = (18,) * 5
NO_SHIFT = 96
HIGHLIGHT_THICKNESS = 1
